# Generated by Django 5.2.1 on 2025-10-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_pengaduan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengaduan',
            old_name='tanggal_lapor',
            new_name='tanggal_pengaduan',
        ),
        migrations.RemoveField(
            model_name='pengaduan',
            name='deskripsi',
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='isi',
            field=models.TextField(default=1, verbose_name='Isi Pengaduan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='judul',
            field=models.CharField(max_length=200, verbose_name='Judul Pengaduan'),
        ),
    ]
